// TODO(@hoodieshq): rename the package to @explorer/idl-decode — the lib is about DECODING data with IDLs, not about IDLs themselves.
// Engine-free entry — decode engines live behind './codama' and './anchor' so processes that never
// decode never load one.
export {
    createIdlClient,
    type IdlClient,
    type IdlClientOptions,
    type IdlMetaClient,
    isAnchorStandard,
    isCodamaStandard,
    tryCreateIdlClient,
} from './client.js';
export type { AccountDataOf, AccountsDataOf, AsDecoded, InstructionDataOf } from './infer.js';
export {
    getIdlProgramVersion,
    getIdlStandard,
    getIdlVersion,
    isAnchorIdl,
    isCodamaIdl,
    isLegacyAnchorIdl,
    isSupportedIdl,
} from './detect.js';
export {
    err,
    getIdlErrorMessage,
    IDL_ERROR__ACCOUNT_DECODE_FAILED,
    IDL_ERROR__DECODE_KIND_MISMATCH,
    IDL_ERROR__DECODE_UNIMPLEMENTED,
    IDL_ERROR__IDL_ADDRESS_MISMATCH,
    IDL_ERROR__IDL_FETCH_FAILED,
    IDL_ERROR__IDL_NOT_FOUND,
    IDL_ERROR__IDL_PARSE_FAILED,
    IDL_ERROR__INSTRUCTION_DECODE_FAILED,
    IDL_ERROR__MISSING_DECODE_HANDLER,
    IDL_ERROR__UNSUPPORTED_IDL_FORMAT,
    IdlError,
    type IdlErrorCode,
    type IdlErrorContext,
    isIdlError,
    ok,
    type Result,
} from './errors.js';
export {
    buildInstructionNameResolver,
    buildInstructionNameTable,
    buildProgramName,
    type InstructionNameEntry,
    type InstructionNameResolver,
    type InstructionNameTable,
    matchInstructionName,
} from './names.js';
export {
    type AccountDecode,
    type AccountDecodeFor,
    type AccountHandlers,
    type AnchorDecodedAccount,
    anchorArm,
    type AnchorDecodedInstruction,
    type AnchorIdl,
    codamaArm,
    type CodamaDecodedAccount,
    type CodamaDecodedInstruction,
    type CodamaIdl,
    type CodamaIdlInput,
    type FallbackDecoder,
    type FallbackDecoderOptions,
    IdlStandard,
    type IdlFetcher,
    type IdlVersion,
    type IdlDecodeProvider,
    type InstructionDecode,
    type InstructionDecodeFor,
    type InstructionHandlers,
    type LegacyAnchorIdl,
    type SupportedIdl,
    type SupportedIdlInput,
    unknownArm,
    unwrap,
} from './types.js';
